images:
- name: kvm
  newName: ghcr.io/anza-labs/kvm-device-plugin
  newTag: v0.2.4
- name: tun
  newName: ghcr.io/anza-labs/tun-device-plugin
  newTag: v0.2.4
namePrefix: kubelet-
namespace: anza-labs-kubelet-plugins
resources:
- ./config/plugin
- ./config/rbac
